events {
    worker_connections 1024;
}

http {
    upstream app_server {
        server app:6969;
    }

    upstream grafana_server {
        server grafana:3000;
    }

    upstream prometheus_server {
        server prometheus:9090;
    }

    server {
        listen 80;

        # Standard APP Access
        location / {
            proxy_pass http://app_server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Protected Observability Tools
        location /prometheus/ {
            auth_basic "Observability Restricted Area";
            auth_basic_user_file /etc/nginx/.htpasswd;
            proxy_pass http://prometheus_server/;
        }

        location /grafana/ {
            proxy_pass http://grafana_server;
            proxy_set_header Host $host;
        }
    }
}
